# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.1'  # Ensure compatibility with Drupal 10
  appServiceName: 'as1-phpwp1'  # Replace with your App Service name
  resourceGroup: 'cloud-training-as1'  # Replace with your Azure Resource Group
  publishFolder: 'publish'


steps:
# 1. Checkout code
- task: Checkout@1

# 2. Setup PHP environment
- task: UsePhpVersion@1
  inputs:
    version: $(phpVersion)
    addToPath: true

# 3. Install dependencies
- script: |
    composer install --no-dev --optimize-autoloader
  displayName: 'Install Composer dependencies'

# 4. Package application
- script: |
    mkdir $(publishFolder)
    cp -R . $(publishFolder)
    # Add any specific packaging or preparation steps
  displayName: 'Prepare application for deployment'

# 5. Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your-Service-Connection>'  # Replace with your Azure service connection
    appType: 'webAppLinux'  # Assuming Linux App Service
    appName: $(appServiceName)
    package: '$(System.DefaultWorkingDirectory)/$(publishFolder)'
    runtimeStack: 'PHP|8.1'

# 6. Run Drupal database updates (optional)
- script: |
    az webapp ssh --name $(appServiceName) --resource-group $(resourceGroup) --command "php /home/site/wwwroot/vendor/drush/drush/drush updb -y"
  displayName: 'Run Drupal database updates'