name: deploy-$(Build.SourceBranchName)-$(Date:dd-MMM-yyyy)
trigger: none
stages:
  - stage: Drupal_Dockerization
    displayName: Dockerization of Drupal and Push to Container Registry
    jobs:
      - job: Dockerization
        steps:
          - task: DownloadSecureFile@1
            displayName: Terraform init
            name: CertificateSSL
            inputs:
              secureFile: 'DigiCertGlobalRootCA.crt.pem'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Agent.TempDirectory)'
              Contents: '*.pem'
              TargetFolder: '$(Build.Repository.LocalPath)'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                find sites/default/settings.php -exec sed -i -- "s/{user}/$(dbuser)/g" {} \;
                find sites/default/settings.php -exec sed -i -- "s/{pass}/$(dbpass)/g" {} \;
#                find settings.php -exec sed -i -- "s/{user}/$(dbuser)/g" {} \;
#                find settings.php -exec sed -i -- "s/{pass}/$(dbpass)/g" {} \;
          - task: Docker@2
            displayName: Dockerizing Drupal
            inputs:
              containerRegistry: 'druaprg'
              repository: 'hello-world'
              command: 'buildAndPush'
              Dockerfile: 'dockerfile'  
  - stage: Drupal_Deployment_az_appserv
    displayName: Drupal Deployment on az app service
    jobs:
      - deployment: Drupal_Deployment_az_appserv
        environment: Drupal-Deployment
        displayName: Drupal Deployment on az app service
        strategy:
          runOnce:
            deploy:  
               steps:
                 - checkout: self
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Free Trial'
                    appType: 'webAppHyperVContainer'
                    WebAppName: 'phpdemoapp1'
                    DockerNamespace: 'druaprg.azurecr.io'
                    DockerRepository: 'hello-world'
                                    